name: Backend Deploy

on:
  push:
    branches:
      - 'main'


jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: github.repository == 'martinbonnin/leonidas'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: hashicorp/setup-terraform@v3
      - name: Build
        run: |
          ./gradlew :leonidas:service-graphql:bumpCloudRunRevision
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
